### ISSUE TITLE
Is there a dbus interface to of-config / openvswitch

### ISSUE THREAD

**Issue by maxmeyer** [openvswitch/of-config#1]
Hi,

is there any other documentation about the API? I found some code mentioning dbus. What is this about? Can this dbus interface be used by some client? Is there any documentation for this I can pass on? Or is there some other api to access openvswitch programmatically via C or dbus?

-> Over at http://lists.freedesktop.org/archives/systemd-devel/ I asked for support of openvswitch in `systemd-nspawn`.

Thanks a lot.

**Comment by rkrejci** [comment]
The OF-CONFIG server is not supposed to provide programatic API. It allows you to communicate with OVS(DB) via OF-CONFIG (NETCONF) protocol. 

D-Bus is used internally for communication between the ofc-server (running as a system daemon) and ofc-agents (which run as SSH Subsystem processes and interconnect OF-CONFIG clients with the ofc-server). You can use this D-Bus interface, but it is very simple and for configuring OVS, there is actually just a single method transfering OF-CONFIG data from ofc-agent to ofc-server. 

Alternativelly, one can use UNIX sockets instead of D-Bus for internal communication described above.

**Comment by maxmeyer** [comment]
Would this be an interface you would support in the long term? Is there any documentation for this interface beside the source code?

**Comment by rkrejci** [comment]
You mean the D-Bus interface? I don't think this is a good idea. Besides the user is allowed to select (by configure option) D-Bus or UNIX socket for this communication, as I said the format of the regular messages to manipulate the configuration data is simple dumped NETCONF RPC message.

As programatic API to OVSDB, you can use OVSDB IDL (as we do). OF-CONFIG (NETCONF) we are implementing is kind of higher level interface you can use e.g. for central control of your network.

**Comment by maxmeyer** [comment]
> As programatic API to OVSDB, you can use OVSDB IDL

Thanks for that hint. Is there any good reference on how to use that api? Googling didn't help that much. 

The only - more or less usable - examples I found are:
- https://github.com/openvswitch/of-config/blob/175ab3394f5a881989fe8b1c40e2db6637f063da/server/ovs-data.c
- https://github.com/osrg/openvswitch/blob/master/lib/ovsdb-idl.h

The documentation in  `ovsdb-idl.h` does not look that helpful, for me a least :smile:. Is there a flow chart or something like that, to get an idea what needs to be done to issue requests using this api, how the data is transferred etc?

**Comment by rkrejci** [comment]
I'm affraid that ovsdb-idl.h (and the commented code of the functions declared there) is the only source of information. The ovs-vsctl tool also uses IDL, so you can inspire there. You can also try to aks in openvswitch's ovs-dev mailing list.

**Comment by maxmeyer** [comment]
Thanks a lot. I passed that information on to the systemd devs...
