### ISSUE TITLE
Question: Modify of-config without OVSDB

### ISSUE THREAD

**Issue by JackLIN-F** [openvswitch/of-config#22]
Hi,
I want to modify this project without OVSDB. Because I am running OpenFlow switch. I will change OVSDB function to OpenFlow function.
Will be the matter concrete and feasible?
Besides, Can I use netopeer-server to install of-config module?

Thanks,
Jack

**Comment by rkrejci** [comment]
Hi, I'm afraid that it is not that simple.

1) this project is focused on OF-CONFIG protocol which runs next to the OpenFlow protocol. They both targets different things (configuration parameters) of an OpenFlow switch, despite they overlap in some parts. OF-CONFIG is mostly used to set OpenFlow switch parameters before it starts while OpenFlow is used to change (different) settings runtime.

2) you can use of-config transAPI module in netopeer-server, but it implements only getter function for status data. Applying the changed configuration data is done via different mechanism provided by libnetconf library - the custom datastore implementation which actually stores configuration data into the OVSDB instead of a file (usually used by Netopeer modules). So you will have to completely reimplement this part.

Regards,
Radek
