### ISSUE TITLE
The connection between netopeer-cli and ofc-server

### ISSUE THREAD

**Issue by xjayjay** [openvswitch/of-config#28]
There is an error  when I use netopeer-cli connecting to ofc-server,as I have started the ofc-server  using the conmand "ofc-server -v 3 -f",and the ofc-server starts successfully.

The error shows below：
root@ubuntu:~# netopeer-cli
netconf> connect --port 830 --login root localhost
libnetconf ERROR: Starting the SSH session failed (Socket error: disconnected)
connect: connecting to the localhost:830 as user "root" failed.

How shoul I solve this problem?

**Comment by rkrejci** [comment]
Are you able to connect directly with ssh?

```
$ ssh localhost -p 830 -l root -s netconf
```

**Comment by xjayjay** [comment]
Yes.It is ok when using "$ ssh localhost -p 830 -l root -s netconf".
I have solved that problem.It seems there are some problems when netopeer-cli connects to ofc-server using libssh.
1# The netopeer-cli works in PC-A,and the ofc-server works in PC-B.
2# The connection between netopeer-cli and ofc-server is only successful if the libnetconf (in PC-A) is configured with "./configure --disable-libssh".
There are two same-name functions  "nc_session_connect_ssh" in "libnetconf/src/ssh.c",the one uses libssh,the other uses openssh.The connection is only ok if the netopeer-cli uses the openssh.

**Comment by aljer-priv** [comment]
I have the same problem but if I configure libnetconf with --disable-libssh I am not able to install netopeer-cli because I receive such an error: 

commands.c:(.text+0x7b34): undefined reference to `nc_set_keypair_path'
commands.c:(.text+0x7f89): undefined reference to `nc_del_keypair_path'
collect2: error: ld returned 1 exit status

I am also able to connect directly with ssh. Only netopeer-cli doent work.
What can I do with this?

I would be grateful for any tips...

Regards,
Ola
