### ISSUE TITLE
Explicitly specify version of OF-Config

### ISSUE THREAD

**Issue by budnyjj** [openvswitch/of-config#5]
As mentioned in https://github.com/openvswitch/of-config/issues/3#issuecomment-84991589, this project implements OF-CONFIG 1.2.

I think, that it would be useful to explicitly specify OF-Config version in requests and answers.
For example,

```
<capable-switch xmlns="urn:onf:config:yang"> => <capable-switch xmlns="urn:onf:of12:config:yang">
```

**Comment by rkrejci** [comment]
YANG has different approach for versioning - the namespace is supposed to be the same (and therefore I personally like the change from onf:of12:config to onf:config) and the versions of data model are specified using the revision statement. The data model revision is announced by the server in its hello message, so the client should check this carefully and do not communicate with the server which does not implement the data model the client expects. As mentioned in #3, ryu does its job wrong way when it ignores the namespace of the received data and stores it into its internal structures implicitly expecting the data model 1.1.1.

**Comment by budnyjj** [comment]
Thank you for explanation!

**Comment by yamt** [comment]
budnyjj,
can you provide a pointer to a specification?
some of examples in OF-CONFIG 1.2 spec use "urn:onf:of12:config:yang".  eg. p.40.

**Comment by rkrejci** [comment]
[OF-CONFIG 1.2 spec](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow-config/of-config-1.2.pdf) mixes 2 namespaces in the examples and the YANG data model then defines the third one, different from those used in examples. I'll pass this issue to ONF, so 1.3 will be consistent. For work with the ofc-server, please use "urn:onf:config:yang" namespace since it is defined in the data model.

**Comment by budnyjj** [comment]
I haven't found any pointers in of-config specifications (v1.1.1, v1.2), what namespace for elements of of-config messages should be used.
